#!/bin/bash
# Quick script to check PowerSync sync status

echo "=== PowerSync Sync Status Check ==="
echo ""
echo "1. Check PowerSync connection status in Console.app:"
echo "   - Open Console.app"
echo "   - Select your iPhone"
echo "   - Filter: 'TobaccoLogistics PowerSync status'"
echo ""
echo "2. Check for errors:"
echo "   - Filter: 'TobaccoLogistics PowerSync error'"
echo ""
echo "3. Check sync progress:"
echo "   - Filter: 'TobaccoLogistics (PowerSync|uploadData|unified_create)'"
echo ""
echo "4. In your app:"
echo "   - Settings → Sync Logs (shows errors)"
echo "   - Check WiFi icon (green = connected, red = disconnected)"
echo ""
echo "=== Common Issues ==="
echo "- PowerSync not connected → Check internet/PowerSync URI"
echo "- Sync stuck → Check for errors in SyncLogs"
echo "- Tables empty → Check if sync completed (green WiFi icon)"
