#!/bin/bash
# Check initial sync logs

echo "=== Checking Initial Sync Logs ==="
echo ""
echo "The login screen should show:"
echo "- Progress percentage"
echo "- Status text (Connecting, Downloading, etc.)"
echo ""
echo "=== Method 1: React Native Logs ==="
echo "Run this command in a terminal:"
echo "npx react-native log-ios | grep -i 'PowerSync\|sync\|🔄\|📊\|✅'"
echo ""
echo "=== Method 2: Console.app (Try These Filters) ==="
echo "1. Just the app name:"
echo "   TobaccoLogistics"
echo ""
echo "2. React Native logs:"
echo "   ReactNativeJS"
echo ""
echo "3. Emoji logs:"
echo "   🔄"
echo ""
echo "4. Progress logs:"
echo "   📊"
echo ""
echo "=== Method 3: Check Login Screen ==="
echo "On your iPhone login screen, look for:"
echo "- Progress bar percentage"
echo "- Status text below progress bar"
echo "- Is it stuck at a specific percentage?"
echo "- What does the status text say?"
echo ""
echo "=== What to Look For ==="
echo "- 'Connecting to PowerSync...' = Not connected yet"
echo "- 'Connected, syncing...' = Connected but no progress"
echo "- 'Downloading data... X%' = Actively syncing"
echo "- 'Sync complete!' = Done (should redirect)"
